name: tasbih_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #DataBase
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #GetX
  get: ^4.6.5
  sqflite: ^2.2.6

  #Provider
  path_provider: ^2.0.14
  path: ^1.8.0


  kartal: ^2.8.0
  vibration: ^1.7.6
  uuid: ^3.0.7
  get_it: ^7.3.0
  flutter_datetime_picker: ^1.5.1
  quickalert: ^1.0.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  #DataBase Generator
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

 
  uses-material-design: true

 
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 